### ISSUE TITLE
Add "proper" HTML documentation

### ISSUE THREAD

**Issue by B1T0** [MHH-RCUG/Wochenende#106]
As the script(s) get more complex, a "proper" documentation generated automatically from source code comments might help to better understand everything. This will help new developers and users to understand what's going on.

Options for that might be
- [Sphinx with autodoc](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html), which is more complex but also more beautiful
- Pydoc, which seems more basic but might be enough

**Comment by B1T0** [comment]
@colindaven

**Comment by colindaven** [comment]
I had a few bad experiences with Sphinx installation in a package once. 

I don't know, I'm a fan of simplicity, and in any case, we need to finish the preprint first. You can write some PRs to improve the docs, particularly the tests and tutorial need a little/lot of work. But also the outputs could be documented differently and names have changed slightly.

cheers

**Comment by B1T0** [comment]
I think I will not focus on it too much but add some comments / docstrings whenever I come across something that is not clear immediately
