### ISSUE TITLE
last refseq used

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/Wochenende#113]
@poer-sophia 

At the moment we need to change -uncomment- the refseq we are using twice.

- in `run_Wochenende.py`
- in `run_Wochenende_reporting_SLURM.sh`

This is a pain, and is error prone.

Idea 1 - set by environment variable. However these can end with the BASH shell which set them. Setting per .bashrc is too permanent, what if I want to change it ?

Idea 2 - preferred. Write the refseq to a temp file in the reporting subfolder, eg `ref.tmp`. This file is constantly overwritten by Wochenende processes and holds only the full path to the ref file. 

It is set by `run_Wochenende.py`

and read by `run_Wochenende_reporting_SLURM.sh`

What do you think @B1T0 @poer-sophia  ?

**Comment by poer-sophia** [comment]
The scond idea sounds good and easy.

**Comment by colindaven** [comment]
Implemented in https://github.com/MHH-RCUG/Wochenende/pull/114
