### ISSUE TITLE
postprocess and haybaler - too many files ?

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/Wochenende#115]
Hi @poer-sophia 

it looks like postprocess is asking haybaler to work on too many files ... i.e., to run for each csv.

Actually it should only run for one set of csv outputs, since only one set can be stored in haybaler

If I look at one csv dir, it contains

reporting/csv

x.ndp.trm.s.bam.txt.rep.s.csv
x.ndp.trm.s.bam.txt.rep.us.csv
x.ndp.trm.s.mm.bam.txt.rep.s.csv
x.ndp.trm.s.mm.bam.txt.rep.us.csv
x.ndp.trm.s.mm.dup.bam.txt.rep.s.csv
x.ndp.trm.s.mm.dup.bam.txt.rep.us.csv
x.ndp.trm.s.mm.dup.mq30.bam.txt.rep.s.csv
x.ndp.trm.s.mm.dup.mq30.bam.txt.rep.us.csv
x.ndp.trm.s.mm.dup.mq30.calmd.bam.txt.rep.s.csv
x.ndp.trm.s.mm.dup.mq30.calmd.bam.txt.rep.us.csv

Should we not set run_haybaler.sh to only work on these files ?
a) mq30.bam.txt.rep.us.csv 
Or should haybaler create an output folder for each file type (of the.us. = unsorted types) ?

What do you think ?

```
# Only run for *bam*.csv if files exist in current dir
count=`ls -1 *.bam*.csv 2>/dev/null | wc -l`
if [ $count != 0 ]
    then
    for csv in $(ls *.bam*.csv)
    do
      python3 haybaler.py -i "$csv" -p . -op $outputDir  -o haybaler.csv
    done
fi

```

**Comment by poer-sophia** [comment]
Oh yes, i think just the mq30.bam.txt.rep.us.csv should be enough. If someone really wants to have haybaler.csv for the other csv, this person can still do this by runnign haybaler manually for different files but i guess the most time noone is interrestet in this.

**Comment by poer-sophia** [comment]
@colindaven But i am not sure if we should change the run_haybaler.sh script or better something in the postprocess script. Because in general I think it should be possible to combine every type of rep.csv, without changeing the code. 
I thougt we could make a haybaler directory with just the wanted files and then run haybaler just for these files. Like a mixture of both of your ideas. So we would have less files but haybaler would still be as "flexible" as before. 

E.g: at the beginnign of the haybaler section in postprocess:
```
mkdir haybaler
cp *mq30.bam*us*.csv haybaler
cd haybaler
# then copy the scripts and run them 
cd ..

# csv to excel transformation 
. . . 

```
What do you think?

**Comment by colindaven** [comment]
Yes, that's a good idea. 
I would additionally add that it should be checked whether files of that type (of csv) have been created at all. If they don't exist, a more general file type should be copied and used (using the count code above, ie..)

count=`ls -1 *mq30.bam*us*.csv 2>/dev/null | wc -l`
if [ $count != 0 ]
    then
    for csv in $(ls *.bam*.csv)
    do
      python3 haybaler.py -i "$csv" -p . -op $outputDir  -o haybaler.csv
    done
fi

Maybe you can remove the haybaler changes to 
run_haybaler.sh
and also implement the changes in postprocess ? 

Thanks

**Comment by poer-sophia** [comment]
That sounds good, yes I can do this.
