### ISSUE TITLE
Configuration Management: Paths, etc.

### ISSUE THREAD

**Issue by B1T0** [MHH-RCUG/Wochenende#125]
TODOs

config needed ?
- [x] analyze all paths and settings needed
- [x] python: seqres links
- [ ] python reporting: ref used (replaces ref.tmp)
- [x] bash: heat trees configured servers 

TODO
- [x] branch `config `created - all work here. No PRs to main, dev, forks etc to maintain functionality until complete
- [x] create simple test config.yaml (CD, SP)
- [x] parse yaml BASH (CD)
- [x] parse yaml python (SP)
- [ ] parse yaml R (SP) is this needed? 
- [x] replace all python run_Wochenende.py settings (SP)
- [x] replace all reporting settings (CD)
- [x] replace all bash haybaler and heat trees settings (SP)
- [ ] add slurm partition and threads to config,yaml - srun- not sbatch only
- [x] test,  test test (all)
- [ ] remove ref.tmp files ? Actually still useful in the reporting folder ..
- [ ] test with singularity  (Tobias)

Setting up all the paths to executables, reference sequences, and adapters in the main script (`run_Wochenende.py`) makes it hard to deal with in a container setting which I try to set up.

I suggest we create a new file, `config.py`, to store the paths there. This will make it easier to find and correct the paths for new users as they don't have to scroll through the whole changelog first and makes it easy to overwrite the file for container usage.

To do so, we just need to copy the code from the main script to the new file and import this new file in the beginning of our main script.

What do you think @colindaven @poer-sophia ?

I could start implementing this in my current work on the containerization.

**Comment by colindaven** [comment]
Hi Tobias, good idea.

We had started this, but didn't use it and hadn't got far with it https://github.com/MHH-RCUG/Wochenende/blob/master/wochenende_conf.sh

It turns out using bash environment vars is quite tricky, so loading them all from a `config.py`  might be a lot more stable.

Note also that Wochenende saves the used reference genome sequence as `ref.tmp `to . and `./reporting`. This way, it can be read from there, and we don't need to specify it in the reporting step again.

You can put the haybaler_path in there as well, as mentioned in the uppermost link: https://github.com/MHH-RCUG/Wochenende/blob/master/wochenende_conf.sh

**Comment by colindaven** [comment]
The classic way to do this is with a json or yaml file. I suggest yaml. Then we need a global yaml file with all settings for Wochenende, Wochenende plot, Wochenende reporting, Haybaler etc. It shouldn't be too hard really. 

Yaml can be parsed easily in Python.
BASH ... well .... not so much ? -> I was wrong: https://github.com/mrbaseman/parse_yaml

**Comment by colindaven** [comment]
I created a TODO list in this issues @B1T0 @poer-sophia

**Comment by poer-sophia** [comment]
I created a new config branch and a conifg.yaml. The first test to implement the run_Wochenende configurations in the yaml and than parse them to the python script instead of configure them directly in the python script worked pretty well.

**Comment by colindaven** [comment]
Hi Sophia, thanks for this. Your config.yaml was too complicated for the bash parser. I created a config_cln.yml using a website yaml validator and committed to branch config.
```

#Usage:
source scripts/parse_yaml.sh
eval $(parse_yaml config_cln.yml)

Now access variables:
#tool
echo path_bwa
#refseq
echo $path_refseq_dict_2021_02_meta_fungi_human_masked

```

Does this new `config_cln.yml `still work with the python parser ?

**Comment by poer-sophia** [comment]
Yes everything works with the cln.yml as well

**Comment by colindaven** [comment]
Nice. I added setup.sh to configure your ~/.bashrc file in some commits to branch config just now. Please test !

**Comment by colindaven** [comment]
Hey @poer-sophia 

have you added this point to haybaler/wochenende config ?
"
 bash: heat trees configured servers
"
I'll add the names of the haybaler and wochenende conda environments as well.

**Comment by poer-sophia** [comment]
Not yet but I wanted to do this today.

**Comment by colindaven** [comment]
So @B1T0 this is config work is complete now and in both dev and master.

**Comment by colindaven** [comment]
Completed
