### ISSUE TITLE
Merge in your fork ?

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/Wochenende#126]
Hi Tobias @B1T0 

when are you planning to merge in your changes ? We should get this done as soon as possible, even if it's not completely finished, to avoid merge hell.

cheers

**Comment by B1T0** [comment]
I just wanted to prepare the merge and mistakenly merged my fork into the master branch. Sorry for that. I will try to undo it now to create a proper pull request

**Comment by colindaven** [comment]
Great, we'll wait for @poer-sophia to have a look at it, and she is away at the moment, but this PR looks good. Thanks
