### ISSUE TITLE
testing branch config

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/Wochenende#137]
Hi Sophia,

can you take a copy of this `/ngsssd1/rcug/wochenende_test/CF_small` elsewhere and test it with the config branches?

eg your .bashrc should look like this:

```
## Config for the metagenome analyzer Wochenende
export WOCHENENDE_DIR=/mnt/ngsnfs/tools/dev/we_config2/Wochenende
export HAYBALER_DIR=/mnt/ngsnfs/tools/dev/we_config2/haybaler
source /mnt/ngsnfs/tools/dev/we_config2/Wochenende/scripts/parse_yaml.sh
eval $(parse_yaml /mnt/ngsnfs/tools/dev/we_config2/Wochenende/config.yaml)



```
It's throwing can't find files errors in the haybaler section

thanks

**Comment by poer-sophia** [comment]
Is it this error? 

Fatal error: cannot open file 'create_heattrees.R': No such file or directory

**Comment by poer-sophia** [comment]
Should be solved in config

**Comment by colindaven** [comment]
I updated the haybaler config branch

run_haybaler.sh was throwing - can't find pandas ....

**Comment by colindaven** [comment]
Instead of rerouting all output to /dev/null from Wochenende_postprocess.sh, do you think we should make a log ? Probably a good idea eh?

**Comment by poer-sophia** [comment]
Yeah that is a really good idea. 
I can't reproduc the pandas error... I even created the haybaler enviroment new from the env.yml because I thougth maybe I changed something with my enviroment but everything still works. I just started Wochenende and than postprocess from the config branch, I have no Idea why you get an error.

**Comment by colindaven** [comment]
Yeah, don't worry, the pandas error I fixed by loading the haybaler env in the script again. I don't generally expect the conda env to be required to  be loaded when I start preprocess or run_haybaler.sh
