### ISSUE TITLE
growth rate code integration

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/Wochenende#145]
Hi @poer-sophia @twehrbein

when integrating Tom's code, Sophia is currently converting bam (big data!) -> bed -> CSV.

https://github.com/MHH-RCUG/Wochenende/blob/dev/growth_rate_code/run_bed_to_csv.sh

This is possible but not efficient. We are already running sambamba depth on the BAM files to get coverage information in windows (but with large windows of 100,000 bp, 50,000 bp step).

https://github.com/MHH-RCUG/Wochenende/blob/master/runbatch_sambamba_depth.sh

So my question - is the coverage information from sambamba depth sufficient for Tom's program ? If not, no problem, we run the bam -> bed -> csv conversion.

**Comment by twehrbein** [comment]
To be honest I don't know, since I have only worked with the provided CSV files so far.
Maybe @poer-sophia can answer this question.

**Comment by poer-sophia** [comment]
I am also not sure. So the output from sambamba_depth counts the reads in windows of 100000 bp if I see this right and then says "in this window are x reads". The input the growth code needs is a single number for the postion of every read. So it probably is possible to get growth rates out of sambamba output but not with the code we have now.

**Comment by colindaven** [comment]
If we need the exact start position of each read then yes, we can't use the existing depth extraction a it's too course. Thanks Sophia.

**Comment by colindaven** [comment]
Hi Sophia,
I'm having problems getting your script - bam to bed, then csv conversion, to run.

I have a test set up here you can try as well (I have already made modifications to link the BAM files in, etc :

`/ngsssd1/rcug/wochenende_test/COPD_small$ bash test_growth_rate.sh
`

It is segfaulting after not resolving the variables properly

` Segmentation fault      (core dumped) python3 bed_to_pos_csv.py -i "${bed%.unfiltered.bed}".bed -p .
`
Any ideas ?

```

INFO: setup.sh should have created  WOCHENENDE_DIR environment variable on this server and user account
INFO: WOCHENENDE_DIR detected as:  /mnt/ngsnfs/tools/dev/Wochenende
INFO: If you get errors here check setup.sh was configured and run properly
INFO: Completed get_wochenende.sh

Version 0.1
bed_to_pos_csv.py                                            COPD_D_MG000061_2020_R1.ndp.trm.s.mm.dup.mq30.calmd.bam.bai  model.py
COPD_D_MG000060_2020_R1.ndp.trm.s.mm.dup.mq30.calmd.bam      COPD_D_MG000062_2020_R1.ndp.trm.s.mm.dup.mq30.calmd.bam      README.txt
COPD_D_MG000060_2020_R1.ndp.trm.s.mm.dup.mq30.calmd.bam.bai  COPD_D_MG000062_2020_R1.ndp.trm.s.mm.dup.mq30.calmd.bam.bai  run_bed_to_csv.sh
COPD_D_MG000061_2020_R1.ndp.trm.s.mm.dup.mq30.calmd.bam      main.py                                                      run_reproduction_determiner.sh
INFO: Starting bed to csv for file COPD_D_MG000060_2020_R1.ndp.trm.s.mm.dup.mq30.calmd.unfiltered.bed
run_bed_to_csv.sh: line 33: 811596 Segmentation fault      (core dumped) python3 bed_to_pos_csv.py -i "${bed%.unfiltered.bed}".bed -p .
INFO: Completed file COPD_D_MG000060_2020_R1.ndp.trm.s.mm.dup.mq30.calmd.unfiltered.bed
INFO: Starting bed to csv for file COPD_D_MG000061_2020_R1.ndp.trm.s.mm.dup.mq30.calmd.unfiltered.bed

```

**Comment by poer-sophia** [comment]
I can't recreate the error... I just started your test script and it worked. I dont get results because you linked the bai instead of bam.txt files and the COPD samples are too small, there is a limit of min. 1000 reads per organism, else no csv will be created, but thats both okay. I will correct the file links but that has nothing to you with your error I guess. So I dont know how I could help you or why you get this error.

**Comment by colindaven** [comment]
Ok thanks. That gave me a good hint the correct wochenende env was not activated! Works now, cheers for the further details too (this is just testing!).

**Comment by colindaven** [comment]
Hi @twehrbein I changed the results csv output to 
`Name,Growth_class,Growth_Rate,No_Reads,Initial_Bins,Used_Bins,Fit_Err,Error_Codes`

(added _ to avoid spaces, replaced "#" with "No_"

@both - works well now though, can be integrated into our postprocessing module so can be auto-calculated by default. 

@poer-sophia with the new environment it works with no problems. Nice that you installed lmfit too.

**Comment by colindaven** [comment]
Code now integrated and working
