### ISSUE TITLE
bedtools

### ISSUE THREAD

**Issue by poer-sophia** [MHH-RCUG/Wochenende#148]
@colindaven Now that this bedtools binary file is deleted I cant use bedtools in bash anymore. You either need to install bedtools via apt-get install bedtools for me or I could see if I can transform bamtobed with a python package and add the package to the wochenende enviroment, so there would be no need for everyone to install bedtools seperately.

**Comment by colindaven** [comment]
Hey, a 40 MB binary available in bioconda is not really appropriate for our repo though, even if it's license conform!

How about via conda 

`conda install -c bioconda bedtools ` (or similar ..)

**Comment by poer-sophia** [comment]
Oh I thought it already was in the my enviroment but I only installed bamtools and not bedtools, my mistake, now it works
