### ISSUE TITLE
python3.7 env error: TypeError: 'LineCollection' object is not iterable

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/Wochenende#153]
After solving above problems now getting LineCollection object not iterable error
```

Traceback (most recent call last):
  File "wochenende_plot.py", line 824, in <module>
    main()
  File "wochenende_plot.py", line 812, in main
    sample_outpath
  File "wochenende_plot.py", line 779, in calculate_scores
    other
  File "wochenende_plot.py", line 515, in generate_output
    simplified_max_mean_coverage,
  File "wochenende_plot.py", line 287, in plot_figures
    for stem in stems:
TypeError: 'LineCollection' object is not iterable
```

**Comment by colindaven** [comment]
https://gitmemory.com/issue/networkx/networkx/3337/515182531

https://matplotlib.org/3.1.1/api/collections_api.html

**Comment by colindaven** [comment]
Not really completely solved, needs to be redesigned to use a collection. But not throwing errors any more and graphs still looking good. What do you think @poer-sophia ?

**Comment by poer-sophia** [comment]
Then I would say its okay.

**Comment by colindaven** [comment]
Solved with https://github.com/MHH-RCUG/Wochenende/pull/154
