### ISSUE TITLE
minimap2 @SQ problem  with many refs

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/Wochenende#17]
Fails when piping directly via samtools to BAM. 

- [x] Must perform intermediate SAM step ?
- [x]  consider ngmlr as alternative aligner ?
- [x] trial --split-prefixes tmpPrefix option

**Comment by colindaven** [comment]
Problem  : old minimap2 2.1.1 being used (!), current is 2.1.17 .

@Colorstorm we need to update the conda environment, best if you did this. 

Command to update minimap2 is:
`conda install -c bioconda minimap2=2.1.17`

**Comment by Colorstorm** [comment]
Ok, I have updated it in my fork, I will run a quick test before creating the PR
