### ISSUE TITLE
wochenende_postprocess raspir error

### ISSUE THREAD

**Issue by irosenboom** [MHH-RCUG/Wochenende#209]
`bash wochenende_postprocess.sh -r -s` terminates with the following error:

```
wochenende_postprocess.sh: line 362: unexpected EOF while looking for matching ``'
wochenende_postprocess.sh: line 389: syntax error: unexpected end of file
```

**Comment by colindaven** [comment]
This is a bug, thanks for reporting. Patched here in dev and main 
https://github.com/MHH-RCUG/Wochenende/pull/210
