### ISSUE TITLE
Integrate reporting as option for human metagenomes

### ISSUE THREAD

**Issue by Colorstorm** [MHH-RCUG/Wochenende#21]
- [x] add code
- [x] add test method 
- [x] update docs

**Comment by Colorstorm** [comment]
It has been done as the reporting script, as a second step

**Comment by colindaven** [comment]
Hi @Colorstorm , does the test method use a defined input and test if the results equal a defined output ? If so, is it all part of the reporting python script ? Has it already been integrated in Wochenende in which PR or commit ? Thanks.
