### ISSUE TITLE
fastp update

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/Wochenende#23]
@colindaven  

fastp program for adapter & quality trimming of raw reads -

- [x]  and we also need to update wochenende pipeline to remove the deprecated options. --
- [x]  update docs to fastp 0.20.0
- [x]  test

cut_by_quality5 DEPRECATED, use --cut_front instead. --cut_by_quality3 DEPRECATED, use --cut_tail instead. --cut_by_quality_aggressive DEPRECATED, use --cut_right instead.

These are the parameters I'm using for trimming SOLID data SE 75bp, fastp -i $file --adapter_fasta $FASTQS_PATH/adapters_solid.fa --cut_front --cut_window_size 5 --cut_mean_quality 15 -l 36 --json $OUT_PATH/${outfile}.trm.json --html $OUT_PATH/${outfile}.trm.html -o $OUT_PATH/${outfile}.trm.fastq

**Comment by colindaven** [comment]
@sannareddyk 

You should be using a fastp which is provided by Miniconda in the wochenende env, so not on the filesystem. 

Thanks for reporting the deprecated parameters.

>       --cut_by_quality5                DEPRECATED, use --cut_front instead.
>       --cut_by_quality3                DEPRECATED, use --cut_tail instead.
>       --cut_by_quality_aggressive      DEPRECATED, use --cut_right instead.

**Comment by sannareddyk** [comment]
@colindaven 
Thanks, currently using fastp version 0.20.0 installed via conda in the wochenende env

**Comment by colindaven** [comment]
@Colorstorm have you added this in your current dev fork ? Thanks

**Comment by colindaven** [comment]
@sannareddyk Can you add the relevant tested changes you want for SOLiD quality adjustment here please ? Thanks

**Comment by colindaven** [comment]
Completed by #31
