### ISSUE TITLE
sambamba and ldc version

### ISSUE THREAD

**Issue by sannareddyk** [MHH-RCUG/Wochenende#24]
Hi,

Ran in to this error while running Wochenende pipeline with the latest version of sambamba( 0.7.1) installed via conda

sambamba: error while loading shared libraries: libphobos2-ldc-shared.so.87: cannot open shared object file: No such file or directory

@colindaven has suggested to pin sambamba=0.6.6 & also pin  ldc=1.11.0

conda install -c conda-forge ldc=1.11.0

**Comment by sannareddyk** [comment]
Pinning sambamba=0.6.6 resolves the issue. 

Couldn't pin ldc=1.11.0 because of some conflicts for other packages.

Similar issues can be found at,
https://github.com/bioconda/bioconda-recipes/issues/11422
https://github.com/bcbio/bcbio-nextgen/issues/3032

**Comment by colindaven** [comment]
Thanks, install docs updated
