### ISSUE TITLE
Conda env

### ISSUE THREAD

**Issue by Colorstorm** [MHH-RCUG/Wochenende#32]
We can create a conda.env.yml file for the Pipeline, afterwards it is easier to configure and to update the conda enviroment.

- [x] Creation of conda.env.yml file
- [x] Adding  to the repo
- [x] Upate dokumentation

**Comment by colindaven** [comment]
@Colorstorm  Need to document exact command for this so we can update this

**Comment by colindaven** [comment]
Never mind, it's
`conda env export > env.wochenende.yml`
