### ISSUE TITLE
perl version mismatch

### ISSUE THREAD

**Issue by sannareddyk** [MHH-RCUG/Wochenende#70]
Wochenende script fails at pcr duplicate removal step with the following error,

ListUtil.c: loadable library and perl binaries are mismatched (got handshake key 0xdb00080, needed 0xcd00080)

OS: Ubuntu 20.04
Perl version: 5.26.2

current conda env file has perl version,
  - perl=5.22.0.1
  - perl-threaded=5.22.0

try updating env.wochenende.yml file to include perl 5.26.2 to resolve compatibility issues.

**Comment by colindaven** [comment]
If your idea doesn't work, try perhaps try completely rebuilding your conda environment on Ubuntu 20.04 ? The perl in conda _should_ be independent of system perl  ....

**Comment by colindaven** [comment]
This link and some strategies looks helpful.
https://forum.manjaro.org/t/perl-seriously-broken/29005/5

Maybe also the perl script used to remove dependencies is not compatible with the new Perl versions on Ubuntu 20.04 ?
If problems continue we'll need to remove and recreate the wochenende conda env - install with Ubuntu 20.04. Probably we need a new conda env definition for 20.04 in this repo too.

There is a hint this could be associated with server load, though that would be counterintuitive. Other users report broken perl dependencies, reboots being necessary, etc.
